-- Replica do schema de producao ANTES das migrations do repositorio,
-- montada a partir do que o banco expoe (colunas observadas em 26/09/2026).
-- Usada so nos testes (PGlite). Tipos "ruins" de proposito (texto em
-- agenda.data/hora, horarios_aluno.dia_semana/horario) para exercitar a conversao.

create role anon nologin;
create role authenticated nologin;

create schema if not exists auth;
grant usage on schema auth to anon, authenticated;
grant usage on schema public to anon, authenticated;
-- logins do Supabase Auth (so o necessario para as FKs)
create table auth.users (id uuid primary key, email text);
create or replace function auth.uid() returns uuid language sql stable as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid
$$;

create table public.alunos (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  nome text not null,
  plano text,
  pagou_em text,
  total_aulas integer not null default 0,
  total integer,
  ativo boolean not null default true,
  aulas_restantes integer not null default 0,
  valor_plano numeric default 0,
  horario text,
  data date,
  data_reinicio date
);

create table public.aulas (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  data date not null,
  status text not null,
  horario time,
  aluno_id uuid references public.alunos(id),
  ativa boolean,
  datas_reinicio date
);

create table public.horarios_aluno (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  aluno_id uuid references public.alunos(id),
  dia_semana text,
  horario text
);

create table public.agenda (
  -- em producao o id da agenda e uuid
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  aluno_id uuid not null,
  hora text,
  data text,
  tipo text,
  observacao text
);
